# Generated by Django 4.2 on 2023-05-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_phone', models.PositiveIntegerField(max_length=10)),
                ('seller_email', models.EmailField(max_length=254)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
